import { Html, Head, Main, NextScript } from "next/document";

export default function Document(contenxt:any) {
  const {locale} = contenxt
  const dir = locale === 'he' ? 'rtl' : 'ltr';
  return (
    <Html lang={locale ?? 'en'} dir={dir}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
