import React, { FC, ReactNode } from "react";
import { HomeWrapper } from "./Home.styled";
import Head from "next/head";

interface HomeProps {
  children: ReactNode;
}

const Home: FC<HomeProps> = ({ children }) => (
  <HomeWrapper>
    <Head>
      <title>Accessibilik</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/AccLanding/favicon.svg" />
    </Head>
    <>{children}</>
  </HomeWrapper>
);

export default Home;
